baseURL = ""
languageCode = "en-gb"
title = "Sketches of Snoak City"
theme = "paperback"
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"
relativeURLs             = true
publishDir               = "docs"                           # for github pages
